#!/usr/bin/env bash

/usr/lib/apt/apt-helper download-file \
    https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb \
    keyring.deb SHA256:2c2601e6053d5c68c2c60bcd088fa9797acec5f285151d46de9c830aaba6173c

sudo apt install ./keyring.deb

echo \
    "deb [signed-by=/usr/share/keyrings/sur5r-keyring.gpg] http://debian.sur5r.net/i3/ $(grep '^VERSION_CODENAME=' /etc/os-release | cut -f2 -d=) universe" | \
    sudo tee /etc/apt/sources.list.d/sur5r-i3.list

sudo apt -y update
sudo apt -y install i3

# status bar
if ! [ -x "$(command -v polybar)" ]; then
    sudo apt install polybar
fi

# screen brightness
if ! [ -x "$(command -v brightnessctl)" ]; then
    sudo apt install brightnessctl
    sudo usermod -aG video $USER
fi

# audio
if ! [ -x "$(command -v pactl)" ]; then
    sudo apt install pactl
fi

# annoying notification
if ! [ -x "$(command -v notify-send)" ]; then
    sudo apt install libnotify-bin
fi

# dmenu replacement
if ! [ -x "$(command -v rofi)" ]; then
    sudo apt install rofi
fi
